apps/investidores/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('sugestoes/', views.sugestoes, name='sugestoes' ),
    path('acessar-empresa/<int:id_emp>/', views.acessar_empresa, name='acessar_empresa'),
    path('realizar-proposta/<int:id_emp>/', views.realizar_proposta, name="realizar_proposta"),
    path('assinar-contrato/<int:id_pi>/', views.assinar_contrato, name='assinar_contrato'),
    path('lista-propostas/', views.lista_propostas, name='lista_propostas'),
    path('dashboard/<int:id_emp>/', views.dashboard, name='dashboard'),
]

core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include, reverse
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('usuarios.urls')),
    path('empresarios/', include('empresarios.urls')),
    path('', lambda home: redirect(reverse('lista_empresas'))),
    path('investidores/', include('investidores.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/empresarios/models.py
from datetime import date, datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe


class Empresa(models.Model):
    estagio_choices = (
        ('I', 'Tenho apenas uma idea'),
        ('MVP', 'Possuo um MVP'),
        ('MVPP', 'Possuo um MVP com clientes pagantes'),
        ('E', 'Empresa pronta para escalar'),
    )
    area_choices = (
        ('ED', 'Ed-tech'),
        ('FT', 'Fintech'),
        ('AT', 'Agrotech'),
        
    )
    alvo_choices = (
        ('B2B', 'Business to Business (B2B)'),
        ('B2C', 'Business to Consumer (B2C)'),
    )
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    nome = models.CharField(max_length=150)
    cnpj = models.CharField(max_length=18, unique=True)
    site = models.URLField()
    inicio_atividade = models.DateField()
    descricao = models.TextField() 
    data_final_captacao = models.DateField()
    percentual_equity = models.PositiveSmallIntegerField() # Percentual esperado
    estagio = models.CharField(max_length=4, choices=estagio_choices, default='I')
    area = models.CharField(max_length=3, choices=area_choices)
    publico_alvo = models.CharField(max_length=3, choices=alvo_choices, default='B2B')
    valor = models.DecimalField(max_digits=9, decimal_places=2) # Valor total a ser vendido
    pitch = models.FileField(upload_to='pitchs')
    logo = models.FileField(upload_to='logo')

    @property
    def tempo_existencia(self):
        dt_hoje = datetime.today().date()
        tempo = (dt_hoje - self.inicio_atividade).days//30
        return tempo # retorna o tempo em meses
    
    @property
    def status(self):
        if date.today() > self.data_final_captacao:
            html = '<span class="badge badge-green">Captação finalizada</span>' 
        else:
            html = '<span class="badge badge-blue">Em captação</span>' 
        return mark_safe(html)
    
    @property
    def valuation(self):
        valor = (100 * self.valor) / self.percentual_equity
        return int(valor*100)/100


    def __str__(self):
        return f'{self.user.username} | {self.nome}'


class Documento(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=40)
    arquivo = models.FileField(upload_to="documentos")

    def __str__(self):
        return self.titulo


class Metrica(models.Model):
    empresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING)
    titulo = models.CharField(max_length=40)
    valor = models.DecimalField(max_digits=9, decimal_places=2)

    def __str__(self):
        return self.titulo

apps/investidores/models.py
from django.db import models
from django.contrib.auth.models import User
from empresarios.models import Empresa


class PropostaInvestimento(models.Model):
    status_choices = (
        ('AA', 'Aguardando assinatura'),
        ('PE', 'Proposta enviada'),
        ('PA', 'Proposta aceita'),
        ('PR', 'Proposta recusada')
    )
    data = models.DateField()
    valor = models.DecimalField(max_digits=9, decimal_places=2)
    percentual = models.FloatField()
    empresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING)
    investidor = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=2, choices=status_choices, default='AA')
    selfie = models.FileField(upload_to="selfie", null=True, blank=True)
    rg = models.FileField(upload_to="rg", null=True, blank=True)

    @property
    def valuation(self):
        return float((100*self.valor)) / self.percentual

    def __str__(self):
        return f'{self.id} | {self.data} | {self.valor}'

apps/investidores/views.py
from datetime import datetime, timedelta
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models.aggregates import Sum
from django.db.models.functions import TruncDay
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from empresarios.models import Documento, Empresa, Metrica
from .models import PropostaInvestimento
from brutils import format_cnpj


@login_required
def sugestoes(request):
    template_name = 'sugestoes.html'
    areas = Empresa.area_choices
    context = {'areas': areas}
    if request.method == "POST":
        tipo = request.POST.get('tipo')
        areas_post = request.POST.getlist('area')
        valor = request.POST.get('valor')

        context['tipo'] = tipo
        context['areas_post'] = areas_post
        context['valor'] = valor

        if len(areas_post) == 0 or len(valor) == 0:
            messages.add_message(request, messages.WARNING, 'Área e/ou valor não informados !')
            return render(request, template_name, context)

        if tipo == 'C':
            empresas = Empresa.objects.filter(inicio_atividade__lte=datetime.today().date() - timedelta(days=1825)).filter(estagio="E") # Mais de 5 anos
        elif tipo == 'D':
            empresas = Empresa.objects.filter(inicio_atividade__gt=datetime.today().date() - timedelta(days=730)).exclude(estagio="E") # Até 2 anos
        elif tipo == 'M':
            empresas = Empresa.objects.filter(inicio_atividade__gt=datetime.today().date() - timedelta(days=1825)).filter(inicio_atividade__lt=datetime.today().date() - timedelta(days=730)).exclude(estagio="E") # De 2 a 5 anos
        
        empresas = empresas.filter(area__in=areas_post)
        
        empresas_selecionadas = []
        for empresa in empresas:
            percentual = (float(valor) * 100) / float(empresa.valuation)
            if percentual >= 1:
                empresas_selecionadas.append(empresa)

        if not empresas_selecionadas:
            messages.add_message(request, messages.WARNING, 'Nenhuma empresa atende aos critérios informados !')
            return render(request, template_name, context)

        context['empresas'] = empresas_selecionadas

        return render(request, template_name, context)

    else:
        return render(request, template_name, context)


@login_required
def acessar_empresa(request, id_emp):
    template_name = 'acessar_empresa.html'
    empresa = get_object_or_404(Empresa, id=id_emp)
    proposta_investimentos = PropostaInvestimento.objects.filter(empresa=empresa)
    percentual_vendido = sum(proposta_investimentos.filter(status='PA').values_list('percentual', flat=True))
    limiar = (80 * empresa.percentual_equity) / 100
    concretizado = False
    if percentual_vendido >= limiar:
        concretizado = True
    percentual_disponivel = empresa.percentual_equity - percentual_vendido

    metricas = Metrica.objects.filter(empresa=empresa)
    documentos = Documento.objects.filter(empresa=empresa)

    context = {
        'empresa': empresa,
        'cnpj_formatado': format_cnpj(empresa.cnpj),
        'percentual_vendido': int(percentual_vendido),
        'concretizado': concretizado,
        'percentual_disponivel': percentual_disponivel,
        'metricas': metricas,
        'documentos': documentos,
    }
    if request.method == 'POST':
        pass
    else:
        return render(request, template_name, context)


@login_required
def realizar_proposta(request, id_emp):
    if request.method == 'POST':
        empresa = get_object_or_404(Empresa, id=id_emp)
        valor = request.POST.get('valor').strip()
        percentual = request.POST.get('percentual').strip()

        if len(valor) == 0 or len(percentual) == 0:
            messages.add_message(request, messages.WARNING, 'Valor e/ou Percentual não informados !')
            return redirect(f'/investidores/acessar-empresa/{id_emp}')

        propostas_aceitas = PropostaInvestimento.objects.filter(empresa=empresa).filter(status='PA')
        total = 0
        for pa in propostas_aceitas:
            total = total + pa.percentual

        if total + int(percentual)  > empresa.percentual_equity:
            messages.add_message(request, messages.WARNING, 'O percentual solicitado ultrapassa o percentual máximo.')
            return redirect(f'/investidores/acessar-empresa/{id_emp}')

        valuation = (100 * int(valor)) / int(percentual)

        if valuation < (int(empresa.valuation) / 2):
            messages.add_message(request, messages.WARNING, f'Seu valuation proposto foi R$ {valuation} e deve ser no mínimo R$ {empresa.valuation/2}')
            return redirect(f'/investidores/acessar-empresa/{id_emp}')

        try:
            pi = PropostaInvestimento(
                data = datetime.today().date(),
                valor = valor,
                percentual = percentual,
                empresa = empresa,
                investidor = request.user,
            )
            pi.save()
        except Exception as e:
            messages.add_message(request, messages.WARNING, f'Erro: {e}')
            return redirect(f'/investidores/acessar-empresa/{id_emp}')

        return redirect(f'/investidores/assinar-contrato/{pi.id}')


@login_required
def assinar_contrato(request, id_pi):
    template_name = 'assinar_contrato.html'
    pi = get_object_or_404(PropostaInvestimento, id=id_pi)
    if pi.status != "AA":
        raise Http404()
    
    if request.method == "POST":
        selfie = request.FILES.get('selfie')
        rg = request.FILES.get('rg')

        if not selfie or not rg:
            messages.add_message(request, messages.WARNING, 'Selfie e/ou RG não informados !')
            return redirect(f'/investidores/assinar-contrato/{id_pi}')

        try:
            pi.selfie = selfie
            pi.rg = rg
            pi.status = 'PE'
            pi.save()
        except Exception as e:
            messages.add_message(request, messages.WARNING, 'Não foi possível assinar o contrato.')
            messages.add_message(request, messages.ERROR, f'Erro: {e}')
            return redirect(f'/investidores/assinar-contrato/{id_pi}')

        messages.add_message(request, messages.SUCCESS, f'Contrato assinado com sucesso, sua proposta foi enviada à empresa.')
        return redirect(f'/investidores/acessar-empresa/{pi.empresa.id}')

    else:
        return render(request, template_name, {'pi': pi})


@login_required
def lista_propostas(request):
    template_name = 'lista_propostas.html'
    propostas = PropostaInvestimento.objects.filter(empresa__user=request.user).exclude(status='AA')
    busca = request.GET.get('empresa')
    if busca:
        propostas = propostas.filter(empresa__nome__icontains=busca)
    context = {
        'propostas' : propostas,
        'concretizado': True,
        'busca': busca,
    }

    return render(request, template_name, context)


@login_required
def dashboard(request, id_emp):
    template_name = 'dashboard.html'
    empresa = Empresa.objects.get(id=id_emp)
    qtd_dias = request.GET.get('qtd-dias')
    ultimo_dia = request.GET.get('ultimo-dia')

    qtd_dias = 7 if not qtd_dias else int(qtd_dias)

    if ultimo_dia:
        ultimo_dia = datetime.strptime(ultimo_dia, '%Y-%m-%d')
    else:
        ultimo_dia = timezone.now().date()

    sete_dias_atras = ultimo_dia - timedelta(days=qtd_dias - 1)

    '''Forma simples

    propostas_diarias = {}

    for i in range(7):
        dia = sete_dias_atras + timedelta(days=i)

        propostas = PropostaInvestimento.objects.filter(
            empresa=empresa,
            status='PA',
            data=dia
        )

        total_dia = 0
        for proposta in propostas:
            total_dia += proposta.valor
        
        propostas_diarias[dia.strftime('%d/%m/%Y')] = float(total_dia)
    '''

    # Forma mais otimizada e avançada
    propostas_diarias = PropostaInvestimento.objects.filter(
        empresa=empresa,
        status='PA',
        data__range=[sete_dias_atras, ultimo_dia]
    ).values('data').annotate(total=Sum('valor')).order_by('data')

    lista_datas = [datetime.strftime(p['data'], '%d/%m/%Y') for p in propostas_diarias]
    lista_totais = [float(p['total']) for p in propostas_diarias]

    context = {
        'qtd_dias': qtd_dias,
        'ultimo_dia': ultimo_dia,
        # 'labels': list(propostas_diarias.keys()),
        # 'valores': list(propostas_diarias.values()),
        'labels': lista_datas,
        'valores': lista_totais,
    }

    return render(request, template_name, context)

apps/investidores/templates/acessar_empresa.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}Investimento empresa{% endblock 'title' %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'geral/css/geral.css' %}">
    <link rel="stylesheet" href="{% static 'geral/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'empresarios/css/empresarios.css' %}">
    <link rel="stylesheet" href="{% static 'investidores/css/investidores.css' %}">
{% endblock 'head' %}

{% block 'body' %}
    <div class="container">
        <div class="mt-4">{% include 'partials/messages.html' %}</div>
        <div class="d-flex gap-5 my-5">
            <div class="w-50">
                <div class="d-flex gap-4 mb-4">
                    <img src="{{empresa.logo.url}}" class="logo" alt="Logo empresa">
                    <div class="d-flex flex-column">
                        <h3>{{empresa.nome}}</h3>
                        <p class="fs-14 mb-4">CNPJ: &nbsp;{{cnpj_formatado}}</p>
                        <span class="badge bg-primary w-60">{{empresa.get_area_display}}</span>
                    </div>
                </div>
                <div class="progress w-70 mb-3">
                    <div class="progress-stacked" style="height: 27px;width: 100%;">
                        <div class="progress" role="progressbar" aria-valuenow="{{percentual_vendido}}" aria-valuemin="0" aria-valuemax="100" style="height: 27px;width: {{percentual_vendido}}%">
                            <div class="progress-bar">{{percentual_vendido|floatformat:'1g'}}</div>
                        </div>
                        <div class="progress" role="progressbar" aria-valuenow="{{empresa.percentual_equity}}" aria-valuemin="0" aria-valuemax="100" style="height: 27px;width: {{empresa.percentual_equity}}%">
                            <div class="progress-bar bg-blue">{{empresa.percentual_equity|floatformat:'1g'}}</div>
                        </div>
                    </div>
                </div>
                
                {% if concretizado %}
                    <span><i class="bi bi-check-lg bg-info"></i>&nbsp; A empresa já atingiu {{percentual_vendido|floatformat:'1g'}}% do percentual captado, portanto seu investimento será concretizado.</span>
                {% else %}
                    <span><i class="bi bi-x-lg bg-warning"></i>&nbsp; Seu investimento será concretizado caso a empresa atinja pelo menos 80% do valor esperado até a data final.</span>
                {% endif %}
                
                <hr>
                <p class="text-justify">{{empresa.descricao}}</p>
                <div class="col-md">
                    <h5>Valuation esperado</h5>
                    <span class="sub-fonte">Esperado: &nbsp;{{empresa.valuation|floatformat:"2g"}}</span>
                    <br>
                    <br>
                    <h5>Percentual</h5>
                    <span class="sub-fonte">Total a venda: &nbsp;{{empresa.percentual_equity}}%</span>
                    <br>
                    <span class="sub-fonte">Disponivel à compra: {{percentual_disponivel}}%</span>
                </div>
                <br>
                <span class="badge bg-warning">{{empresa.publico_alvo}}</span>
                <br><br>
                <h4 style="color: #92D5EB">Indicadores |</h4>     
                <div class="d-flex flex-wrap column-gap-5 row-gap-4 my-4">
                    {% for metrica in metricas %}
                        <div class="w-40 bg-color-dark text-center fw-700 p-4">
                            <p class="fs-18">{{metrica.titulo}}</p>
                            <p class="fs-4 mb-0">R$ {{metrica.valor}}</p>
                        </div>
                    {% empty %}
                        <p class="bg-color-dark fs-18 p-3 mb-0">Nenhuma métrica cadastrada !</p>
                    {% endfor %}
                </div>

                <hr>
                <h4>Faça sua proposta</h4>
                <form action="{% url 'realizar_proposta' empresa.id %}" method="POST"> 
                    {% csrf_token %}
                    <div class="d-flex gap-4 mt-4">
                        <input type="number" name="valor" class="form-control" placeholder="Valor para investir">
                        <input type="number" name="percentual" class="form-control" placeholder="% desejado">
                        <input type="submit" class="btn-cadastro bsm-px20" value="Salvar">
                    </div>
                </form>
                    
            </div>
            <div class="w-50 intereses-investimentos">
                <video name='demo' controls autoplay width='100%'>
                    <source src="{{empresa.pitch.url}}" type="video/mp4"></source>
                </video>

                <hr>
                <h3>Documentos</h3>
                <div class="list_documentos">
                    {% for doc in documentos %}
                    <div class="row bg-color-dark py-2 mx-0 mb-2">
                        <div class="col-md-1" style="text-align: center">
                            <a href="{{doc.arquivo.url}}" target="_blank">
                                <i class="bi bi-download"></i>
                            </a>
                        </div>
                        <div class="col-md-10">{{doc.titulo}}</div>
                        <div class="col-md-1" style="text-align: right;">
                            <a href="{% url 'excluir_doc' doc.id %}">
                                <i class="bi bi-x-lg"></i>
                            </a>
                        </div>
                    </div>
                    {% empty %}
                        <p class="bg-color-dark color-secondary p-2">Não existe documento anexado !</p>
                    {% endfor %}
                </div>
                
            </div>
        </div>
    </div>
{% endblock 'body' %}

apps/investidores/templates/assinar_contrato.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}Investimento empresa{% endblock 'title' %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'geral/css/geral.css' %}">
    <link rel="stylesheet" href="{% static 'geral/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'empresarios/css/empresarios.css' %}">
    <link rel="stylesheet" href="{% static 'investidores/css/investidores.css' %}">
{% endblock 'head' %}


{% block 'body' %}
    <div class="container">
        <div class="row align-items-center mt-5">
            <div class="col-md-3">
                <img src="{{pi.empresa.logo.url}}" class="logo" alt="Logo da empresa">
            </div>
            <div class="col-md">
                <h3>Assinar contrato</h3>
            </div>
        </div>    
        <div class="mt-3">
            {% include 'partials/messages.html' %}
        </div>
        <div class="contrato mt-5">
            <h3>Contrato de investimento</h3>
            <p>Ao assinar esse contrato você concorda com todas as cláusulas abaixo</p>
            
            <ol>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
                <li>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy</li>
            </ol>
        </div>
        <form action="{% url 'assinar_contrato' pi.id %}" enctype='multipart/form-data' method="POST">
            {% csrf_token %}
            <div class="w-70 mt-5">
                <div class="mb-3">
                    <label for="selfie">Selfie</label>
                    <input type="file" name="selfie" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="rg">RG</label>
                    <input type="file" name="rg" class="form-control">
                </div>
                <br>
                <mb class="mb-3">
                    <input type="submit" class="btn-cadastro bsm-px20 w-40" value="Assinar">
                </mb>
            </div>
        </form>
    </div>
{% endblock 'body' %}

apps/investidores/templates/dashboard.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}Dashboard{% endblock 'title' %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'geral/css/geral.css' %}">
    <link rel="stylesheet" href="{% static 'geral/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'empresarios/css/empresarios.css' %}">
    <link rel="stylesheet" href="{% static 'investidores/css/investidores.css' %}">
{% endblock 'head' %}

{% block 'body' %}
    <div class="container inter">
        <div class="w-75 mt-5">
            <div class="d-flex align-items-center gap-4 mb-4">
                <h3 class="mb-0">Propostas aceitas no período de</h3>
                <select class="form-select w-20" name="qtd-dias" id="qtd-dias">
                    <option value="7" {% if qtd_dias == 7 %}selected{% endif %}>7 dias</option>
                    <option value="15" {% if qtd_dias == 15 %}selected{% endif %}>15 dias</option>
                    <option value="30" {% if qtd_dias == 30 %}selected{% endif %}>30 dias</option>
                </select>
            </div>
            <div class="d-flex align-items-center gap-4 mb-4">
                <label for="ultimo-dia" class="form-label">Último dia do período:</label>
                <input type="date" class="form-control data" name="ultimo-dia" id="ultimo-dia" value="{{ultimo_dia|date:'Y-m-d'}}">
                <a href="#" id="remover-filtro" class="d-flex btn btn-secundario bsm-px10 align-items-center" data-bs-tt="tooltip" data-bs-title="Remover filtro"><i class="bi bi-arrow-counterclockwise"></i></a>
            </div>
            
            {% if not valores %}
                <p class="bg-color-dark fs-3 fw-700 p-4 b-radius">Nenhuma proposta aceita no período !</p>
            {% else %}
                <canvas id="barChart"></canvas>
            {% endif %}
                
        </div>

        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
            const el_ultimo_dia = document.getElementById('ultimo-dia');
            const el_qtd_dias = document.getElementById('qtd-dias');
            const el_remover_filtro = document.getElementById('remover-filtro');
            const ctx = document.getElementById('barChart');
            const data = {
                labels: {{labels|safe}},
                datasets: [
                    {
                        label: 'Investimento recebido',
                        backgroundColor: 'rgb(255, 99, 132, 0.2)',
                        borderColor: 'rgb(255, 99, 132)',
                        borderWidth: 1,
                        data: {{valores|safe}},
                    },
                ]
            };

            new Chart(ctx, {
                    type: 'bar',
                    data: data,
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true,
                            }
                        }
                    }
            });
            
            el_ultimo_dia.addEventListener('change', () => {
                const url_params = new URLSearchParams(window.location.search);
                url_params.set('ultimo-dia', el_ultimo_dia.value);
                window.location.search = url_params;
            });
            el_qtd_dias.addEventListener('change', () => {
                const url_params = new URLSearchParams(window.location.search);
                url_params.set('qtd-dias', el_qtd_dias.value);
                window.location.search = url_params;
            });
            el_remover_filtro.addEventListener('click', () => {
                const url_params = new URLSearchParams(window.location.search);
                url_params.delete('qtd-dias', el_qtd_dias.value);
                url_params.delete('ultimo-dia', el_ultimo_dia.value);
                window.location.search = url_params;
            });

        </script>
    </div>
{% endblock 'body' %}

apps/investidores/templates/lista_propostas.html
{% extends "base.html" %}
{% load static %}

{% block 'title' %}Lista propostas de investimentos{% endblock 'title' %}

{% block 'head' %}
    <link rel="stylesheet" href="{% static 'geral/css/geral.css' %}">
    <link rel="stylesheet" href="{% static 'geral/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'usuarios/css/usuarios.css' %}">
    <link rel="stylesheet" href="{% static 'empresarios/css/empresarios.css' %}">
{% endblock 'head' %}

{% block 'body' %}
    <div class="container inter">
        {% include "partials/messages.html" %}
        <form action="{% url 'lista_propostas' %}" method="GET">
            <div class="d-flex align-items-end gap-4 mt-4">
                <div class="">
                    <label>Empresa</label>
                    <input type="text" class="form-control" name="empresa" placeholder="Informe o nome da empresa" 
                    {% if busca %}
                        value="{{busca}}"
                    {% endif %} autofocus>
                </div>
                <input type="submit" class="btn-cadastro bsm-px20" value="Filtrar">
                <a href="{% url 'lista_propostas' %}" class="btn-secundario bsm-px10 d-flex align-items-center" data-bs-tt="tooltip" data-bs-title="Remover filtro"><i class="bi bi-arrow-counterclockwise"></i></a>
            </div>
        </form>
        <div class="bg-color-dark p-5">
            {% if propostas %}
                <table class="table align-middle mb-0">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Empresa</th>
                            <th scope="col">Percentual captado</th>
                            <th scope="col">Status</th>
                            <th scope="col" class="text-center">Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for proposta in propostas  %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{proposta.empresa.nome}}</td>
                                <td>
                                    <div class="progress" role="progressbar" aria-valuenow="{{proposta.percentual}}" aria-valuemin="0" aria-valuemax="100">
                                        <div class="progress-bar" style="width: {{proposta.percentual}}%">{{proposta.percentual|floatformat:'1g'}}</div>
                                    </div>
                                </td>
                                <td>
                                    <span class="w-70 badge 
                                        {% if proposta.status == 'PA' %}
                                            badge-green
                                        {% elif proposta.status == 'PE' %}
                                            badge-blue
                                        {% elif proposta.status == 'PR' %}
                                            bg-danger
                                        {% endif %}">
                                        {{proposta.get_status_display}}
                                    </span>
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'ver_empresa' proposta.empresa.id %}" class="btn-cadastro
                                        {% if proposta.status in 'PAPR' %}
                                            not-active
                                        {% endif %}"
                                    >Decidir</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p class="fs-3 fw-600 text-center mb-0">Que pena, ainda não há empresa investidora !</p>
            {% endif %}
                
        </div>
    </div>
{% endblock 'body' %}